import type {
  BudgetCategory,
  PulseState,
  Transaction,
  CategoryId,
} from "./types";
import { addDaysISO, todayISO, uid } from "./format";

export const STATE_VERSION = 1;
export const STORAGE_KEY = "pulse-ai-state-v1";

export const CATEGORY_META: Record<
  CategoryId,
  { name: string; kind: "fixed" | "variable" }
> = {
  housing: { name: "Housing", kind: "fixed" },
  utilities: { name: "Utilities", kind: "fixed" },
  groceries: { name: "Groceries", kind: "variable" },
  transportation: { name: "Transportation", kind: "fixed" },
  subscriptions: { name: "Subscriptions", kind: "fixed" },
  dining: { name: "Dining", kind: "variable" },
  shopping: { name: "Shopping", kind: "variable" },
  entertainment: { name: "Entertainment", kind: "variable" },
  health: { name: "Health", kind: "fixed" },
  education: { name: "Education", kind: "fixed" },
  other: { name: "Other", kind: "variable" },
};

/** Budgets: fixed sums to $2,340 · variable sums to $1,120 */
const CATEGORY_BUDGETS: Record<CategoryId, { budget: number; lastMonth: number }> = {
  housing: { budget: 1450, lastMonth: 1450 },
  utilities: { budget: 195, lastMonth: 188 },
  transportation: { budget: 280, lastMonth: 274 },
  subscriptions: { budget: 85, lastMonth: 97 },
  health: { budget: 130, lastMonth: 130 },
  education: { budget: 200, lastMonth: 200 },
  groceries: { budget: 420, lastMonth: 405 },
  dining: { budget: 260, lastMonth: 242 },
  shopping: { budget: 200, lastMonth: 178 },
  entertainment: { budget: 140, lastMonth: 122 },
  other: { budget: 100, lastMonth: 84 },
};

function seedCategories(): BudgetCategory[] {
  return (Object.keys(CATEGORY_META) as CategoryId[]).map((id) => ({
    id,
    name: CATEGORY_META[id].name,
    kind: CATEGORY_META[id].kind,
    budget: CATEGORY_BUDGETS[id].budget,
    lastMonth: CATEGORY_BUDGETS[id].lastMonth,
  }));
}

/** [daysAgo, name, category, amount, type] */
type TxSpec = [number, string, Transaction["category"], number, Transaction["type"]];

const TX_SPECS: TxSpec[] = [
  [1, "Verde Coffee Roasters", "dining", 6.4, "expense"],
  [1, "Whole Harvest Market", "groceries", 62.18, "expense"],
  [2, "Lyra Rideshare", "transportation", 14.5, "expense"],
  [2, "Paycheck · Meridian Studio", "income", 2425, "income"],
  [2, "Nova Streaming", "subscriptions", 15.99, "expense"],
  [3, "Saffron & Vine Bistro", "dining", 48.75, "expense"],
  [4, "Cloudpage Pro", "subscriptions", 12, "expense"],
  [4, "Auto transfer → savings", "savings", 215, "transfer"],
  [5, "Juniper Apparel", "shopping", 84.3, "expense"],
  [6, "Whole Harvest Market", "groceries", 54.62, "expense"],
  [6, "City Transit Pass", "transportation", 25, "expense"],
  [7, "Kindle Books", "entertainment", 11.99, "expense"],
  [8, "Golden Wok Express", "dining", 27.4, "expense"],
  [9, "Solstice Yoga Studio", "health", 32, "expense"],
  [10, "Pixel Cinema", "entertainment", 24.5, "expense"],
  [10, "Whole Harvest Market", "groceries", 71.05, "expense"],
  [11, "Credit card payment", "debt", 96, "transfer"],
  [11, "Marble Home Goods", "shopping", 63.75, "expense"],
  [12, "Brightline Internet", "utilities", 64.99, "expense"],
  [13, "Verde Coffee Roasters", "dining", 5.9, "expense"],
  [13, "Student loan payment", "debt", 110, "transfer"],
  [14, "Copper Kettle Brunch", "dining", 38.2, "expense"],
  [15, "Whole Harvest Market", "groceries", 58.44, "expense"],
  [16, "Paycheck · Meridian Studio", "income", 2425, "income"],
  [16, "Rent · Alder House Apartments", "housing", 1450, "expense"],
  [17, "City Power & Light", "utilities", 88.35, "expense"],
  [17, "Waveform Music", "subscriptions", 10.99, "expense"],
  [18, "Fuel · Northgate Station", "transportation", 41.6, "expense"],
  [19, "Aster Pharmacy", "health", 22.8, "expense"],
  [19, "Auto transfer → savings", "savings", 215, "transfer"],
  [20, "Juniper Apparel", "shopping", 47.9, "expense"],
  [21, "Night Market Tacos", "dining", 31.65, "expense"],
  [22, "Whole Harvest Market", "groceries", 66.9, "expense"],
  [23, "Lumen Design Course", "education", 200, "expense"],
  [24, "Verde Coffee Roasters", "dining", 12.8, "expense"],
  [25, "Pixel Cinema", "entertainment", 18, "expense"],
  [25, "Watercolor supplies", "shopping", 36.2, "expense"],
  [26, "Golden Wok Express", "dining", 24.15, "expense"],
  [27, "Whole Harvest Market", "groceries", 49.75, "expense"],
  [28, "City Water Utility", "utilities", 38.6, "expense"],
  [29, "Trailhead Gear Co.", "shopping", 42.5, "expense"],
  [29, "Birthday dinner · Saffron & Vine", "dining", 86.4, "expense"],
];

function seedTransactions(today: string): Transaction[] {
  return TX_SPECS.map(([daysAgo, name, category, amount, type]) => ({
    id: uid("tx"),
    date: addDaysISO(today, -daysAgo),
    name,
    category,
    amount,
    type,
  }));
}

export function createSeedState(overrides?: {
  name?: string;
  riskLevel?: PulseState["profile"]["riskLevel"];
  coachingStyle?: PulseState["profile"]["coachingStyle"];
}): PulseState {
  const today = todayISO();
  const efId = uid("goal");

  return {
    version: STATE_VERSION,
    profile: {
      name: overrides?.name ?? "Amy",
      currency: "USD",
      riskLevel: overrides?.riskLevel ?? "balanced",
      coachingStyle: overrides?.coachingStyle ?? "direct",
      onboarded: true,
      joinedAt: today,
    },
    monthlyIncome: 4850,
    savingsBalance: 7850,
    emergencyFundGoalId: efId,
    categories: seedCategories(),
    transactions: seedTransactions(today),
    goals: [
      {
        id: efId,
        name: "Emergency Fund",
        icon: "shield",
        target: 12000,
        current: 6100,
        deadline: addDaysISO(today, 420),
        priority: 1,
        monthlyContribution: 430,
      },
      {
        id: uid("goal"),
        name: "Travel Fund",
        icon: "plane",
        target: 4000,
        current: 1350,
        deadline: addDaysISO(today, 300),
        priority: 3,
        monthlyContribution: 120,
      },
      {
        id: uid("goal"),
        name: "Home Down Payment",
        icon: "home",
        target: 45000,
        current: 3200,
        deadline: addDaysISO(today, 1650),
        priority: 4,
        monthlyContribution: 150,
      },
      {
        id: uid("goal"),
        name: "Debt Freedom",
        icon: "unlock",
        target: 11250,
        current: 1650,
        deadline: addDaysISO(today, 640),
        priority: 2,
        monthlyContribution: 281,
      },
      {
        id: uid("goal"),
        name: "Retirement",
        icon: "sunrise",
        target: 500000,
        current: 18420,
        deadline: addDaysISO(today, 365 * 30),
        priority: 5,
        monthlyContribution: 300,
      },
    ],
    debts: [
      { id: uid("debt"), name: "Sapphire Rewards Card", balance: 3200, apr: 24.99, minPayment: 96 },
      { id: uid("debt"), name: "Federal Student Loan", balance: 6400, apr: 6.2, minPayment: 110 },
    ],
    portfolio: {
      totalValue: 18420,
      monthlyContribution: 300,
      startValue: 15900,
      allocation: { usStocks: 52, intlStocks: 18, bonds: 14, cash: 8, alternatives: 8 },
    },
    tasks: [
      {
        id: uid("task"),
        title: "Move $250 to emergency fund",
        detail: "Your checking balance can absorb this today without touching bills. It moves the emergency fund past the halfway mark.",
        bucket: "today",
        priority: "high",
        impact: 250,
        due: today,
        timeNeeded: "2 min",
        category: "Savings",
        status: "open",
        effect: { kind: "moveToSavings", amount: 250 },
      },
      {
        id: uid("task"),
        title: "Pay an extra $75 toward the Sapphire card",
        detail: "Every extra $75 at 24.99% APR saves about $19 in interest over the next year and shortens the payoff by 12 days.",
        bucket: "week",
        priority: "high",
        impact: 75,
        due: addDaysISO(today, 4),
        timeNeeded: "3 min",
        category: "Debt",
        status: "open",
        effect: { kind: "payDebt", amount: 75 },
      },
      {
        id: uid("task"),
        title: "Cancel the unused Cloudpage Pro subscription",
        detail: "No logins in 60 days. Cancelling frees $12 every month — $144 a year back into your plan.",
        bucket: "week",
        priority: "medium",
        impact: 144,
        due: addDaysISO(today, 6),
        timeNeeded: "5 min",
        category: "Subscriptions",
        status: "open",
        effect: { kind: "cutCategoryBudget", category: "subscriptions", amount: 12 },
      },
      {
        id: uid("task"),
        title: "Set a $65 weekly dining cap",
        detail: "Dining is trending 18% above normal. A soft cap keeps the month on budget without cutting it entirely.",
        bucket: "week",
        priority: "medium",
        impact: 45,
        due: addDaysISO(today, 6),
        timeNeeded: "1 min",
        category: "Spending",
        status: "open",
        effect: { kind: "none" },
      },
      {
        id: uid("task"),
        title: "Automate a $150 payday transfer to savings",
        detail: "Money you never see is money you never miss. Scheduling on payday removes the willpower step.",
        bucket: "month",
        priority: "medium",
        impact: 150,
        due: addDaysISO(today, 13),
        timeNeeded: "10 min",
        category: "Savings",
        status: "open",
        effect: { kind: "none" },
      },
      {
        id: uid("task"),
        title: "Get a renewal quote for car insurance",
        detail: "Your policy renews in September. Two comparison quotes typically save $180–$320 a year.",
        bucket: "month",
        priority: "low",
        impact: 250,
        due: addDaysISO(today, 24),
        timeNeeded: "25 min",
        category: "Insurance",
        status: "open",
        effect: { kind: "none" },
      },
      {
        id: uid("task"),
        title: "Raise investing to $400/mo once the card is paid off",
        detail: "When the Sapphire card hits zero, its $96 minimum plus extra payments can roll straight into your index contributions.",
        bucket: "longTerm",
        priority: "low",
        impact: 1200,
        due: addDaysISO(today, 180),
        timeNeeded: "5 min",
        category: "Investing",
        status: "open",
        effect: { kind: "none" },
      },
    ],
    opportunities: [
      {
        id: uid("opp"),
        title: "Trim $34/month from subscriptions",
        gain: 34,
        gainLabel: "$34/mo · $408/yr",
        difficulty: "easy",
        time: "10 min",
        impact: "medium",
        why: "You carry 6 subscriptions totaling $97/month against an $85 budget. Two show no activity in 60 days.",
        calculation: "Cloudpage Pro ($12) + Waveform duplicate plan ($10.99) + annual-plan switch on Nova (−$11) ≈ $34/month.",
        badges: ["Quick Win"],
        status: "new",
        effect: { kind: "cutCategoryBudget", category: "subscriptions", amount: 34 },
      },
      {
        id: uid("opp"),
        title: "Pay the Sapphire card first — save $412",
        gain: 412,
        gainLabel: "$412 interest saved",
        difficulty: "medium",
        time: "Ongoing",
        impact: "high",
        why: "At 24.99% APR the card costs 4× more per dollar than the student loan at 6.2%. Avalanche order wins here.",
        calculation: "Directing your $281/mo debt budget at the card first clears it in ~13 months and avoids ≈$412 of interest vs. splitting payments evenly.",
        badges: ["High Impact"],
        status: "new",
      },
      {
        id: uid("opp"),
        title: "Move emergency fund to a 4.4% APY account",
        gain: 288,
        gainLabel: "+$288/yr interest",
        difficulty: "easy",
        time: "20 min",
        impact: "medium",
        why: "Your $7,850 in savings earns roughly 0.7% today. A high-yield account pays about 4.4% with the same FDIC coverage.",
        calculation: "$7,850 × (4.4% − 0.7%) ≈ $290 in the first year, compounding after that.",
        badges: ["Quick Win", "Long-Term"],
        status: "new",
      },
      {
        id: uid("opp"),
        title: "Lower dining spend by $45 this week",
        gain: 45,
        gainLabel: "$45 this week",
        difficulty: "medium",
        time: "This week",
        impact: "medium",
        why: "Dining is pacing 18% over its normal level. Pulling back now protects your safe-to-spend for the rest of the month.",
        calculation: "Trailing 30-day dining is running past its $260 budget. Two home-cooked dinners and one skipped brunch ≈ $45.",
        badges: ["Quick Win", "Urgent"],
        status: "new",
      },
      {
        id: uid("opp"),
        title: "Raise investing by $100/mo after the card is paid",
        gain: 1200,
        gainLabel: "+$18.9K in 10 yrs",
        difficulty: "easy",
        time: "After payoff",
        impact: "high",
        why: "Once the 24.99% card is gone, that cash flow earns instead of costs. Sequencing matters more than timing the market.",
        calculation: "$100/mo at 7% average annual growth compounds to ≈ $17,300–$18,900 over 10 years.",
        badges: ["Long-Term", "High Impact"],
        status: "new",
      },
      {
        id: uid("opp"),
        title: "Set aside $90/mo for September's insurance bill",
        gain: 540,
        gainLabel: "Avoids a $540 shock",
        difficulty: "easy",
        time: "5 min",
        impact: "medium",
        why: "Your annual car insurance premium (~$540) lands in September. Spreading it across two months keeps that week out of the red.",
        calculation: "$540 ÷ 6 remaining pay periods = $90 per paycheck into a holding buffer.",
        badges: ["Risk Reduction", "Urgent"],
        status: "new",
      },
    ],
    decisions: [],
    recommendations: [],
    notifications: [
      {
        id: uid("ntf"),
        title: "Dining trend alert",
        body: "Dining is 18% above its usual pace. Pulse suggests a $65 weekly cap through month-end.",
        time: "2h ago",
        read: false,
        tone: "warn",
      },
      {
        id: uid("ntf"),
        title: "Paycheck received",
        body: "$2,425 from Meridian Studio landed in checking. $215 auto-saved per your plan.",
        time: "2d ago",
        read: false,
        tone: "good",
      },
      {
        id: uid("ntf"),
        title: "New opportunity found",
        body: "Switching your emergency fund to a 4.4% APY account would earn ≈$288/yr.",
        time: "3d ago",
        read: true,
        tone: "info",
      },
    ],
    flags: {},
  };
}
